# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cise/homes/yupeng/workspace/ucm-mpi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cise/homes/yupeng/workspace/ucm-mpi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cise/homes/yupeng/workspace/ucm-mpi/CMakeFiles /cise/homes/yupeng/workspace/ucm-mpi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cise/homes/yupeng/workspace/ucm-mpi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ucm-mpi

# Build rule for target.
ucm-mpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ucm-mpi
.PHONY : ucm-mpi

# fast build rule for target.
ucm-mpi/fast:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/build
.PHONY : ucm-mpi/fast

#=============================================================================
# Target rules for targets named buildW

# Build rule for target.
buildW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buildW
.PHONY : buildW

# fast build rule for target.
buildW/fast:
	$(MAKE) -f buildW/CMakeFiles/buildW.dir/build.make buildW/CMakeFiles/buildW.dir/build
.PHONY : buildW/fast

#=============================================================================
# Target rules for targets named CSparse

# Build rule for target.
CSparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CSparse
.PHONY : CSparse

# fast build rule for target.
CSparse/fast:
	$(MAKE) -f CSparse/CMakeFiles/CSparse.dir/build.make CSparse/CMakeFiles/CSparse.dir/build
.PHONY : CSparse/fast

#=============================================================================
# Target rules for targets named damascene

# Build rule for target.
damascene: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 damascene
.PHONY : damascene

# fast build rule for target.
damascene/fast:
	$(MAKE) -f damascene/CMakeFiles/damascene.dir/build.make damascene/CMakeFiles/damascene.dir/build
.PHONY : damascene/fast

#=============================================================================
# Target rules for targets named globalPb

# Build rule for target.
globalPb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 globalPb
.PHONY : globalPb

# fast build rule for target.
globalPb/fast:
	$(MAKE) -f globalPb/CMakeFiles/globalPb.dir/build.make globalPb/CMakeFiles/globalPb.dir/build
.PHONY : globalPb/fast

src/GLSVM.o: src/GLSVM.cpp.o

.PHONY : src/GLSVM.o

# target to build an object file
src/GLSVM.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/GLSVM.cpp.o
.PHONY : src/GLSVM.cpp.o

src/GLSVM.i: src/GLSVM.cpp.i

.PHONY : src/GLSVM.i

# target to preprocess a source file
src/GLSVM.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/GLSVM.cpp.i
.PHONY : src/GLSVM.cpp.i

src/GLSVM.s: src/GLSVM.cpp.s

.PHONY : src/GLSVM.s

# target to generate assembly for a file
src/GLSVM.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/GLSVM.cpp.s
.PHONY : src/GLSVM.cpp.s

src/MATLAB_functions.o: src/MATLAB_functions.cpp.o

.PHONY : src/MATLAB_functions.o

# target to build an object file
src/MATLAB_functions.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/MATLAB_functions.cpp.o
.PHONY : src/MATLAB_functions.cpp.o

src/MATLAB_functions.i: src/MATLAB_functions.cpp.i

.PHONY : src/MATLAB_functions.i

# target to preprocess a source file
src/MATLAB_functions.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/MATLAB_functions.cpp.i
.PHONY : src/MATLAB_functions.cpp.i

src/MATLAB_functions.s: src/MATLAB_functions.cpp.s

.PHONY : src/MATLAB_functions.s

# target to generate assembly for a file
src/MATLAB_functions.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/MATLAB_functions.cpp.s
.PHONY : src/MATLAB_functions.cpp.s

src/SPFeatures.o: src/SPFeatures.cpp.o

.PHONY : src/SPFeatures.o

# target to build an object file
src/SPFeatures.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/SPFeatures.cpp.o
.PHONY : src/SPFeatures.cpp.o

src/SPFeatures.i: src/SPFeatures.cpp.i

.PHONY : src/SPFeatures.i

# target to preprocess a source file
src/SPFeatures.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/SPFeatures.cpp.i
.PHONY : src/SPFeatures.cpp.i

src/SPFeatures.s: src/SPFeatures.cpp.s

.PHONY : src/SPFeatures.s

# target to generate assembly for a file
src/SPFeatures.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/SPFeatures.cpp.s
.PHONY : src/SPFeatures.cpp.s

src/UCMgenerator.o: src/UCMgenerator.cpp.o

.PHONY : src/UCMgenerator.o

# target to build an object file
src/UCMgenerator.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/UCMgenerator.cpp.o
.PHONY : src/UCMgenerator.cpp.o

src/UCMgenerator.i: src/UCMgenerator.cpp.i

.PHONY : src/UCMgenerator.i

# target to preprocess a source file
src/UCMgenerator.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/UCMgenerator.cpp.i
.PHONY : src/UCMgenerator.cpp.i

src/UCMgenerator.s: src/UCMgenerator.cpp.s

.PHONY : src/UCMgenerator.s

# target to generate assembly for a file
src/UCMgenerator.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/UCMgenerator.cpp.s
.PHONY : src/UCMgenerator.cpp.s

src/buildW.o: src/buildW.cpp.o

.PHONY : src/buildW.o

# target to build an object file
src/buildW.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/buildW.cpp.o
.PHONY : src/buildW.cpp.o

src/buildW.i: src/buildW.cpp.i

.PHONY : src/buildW.i

# target to preprocess a source file
src/buildW.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/buildW.cpp.i
.PHONY : src/buildW.cpp.i

src/buildW.s: src/buildW.cpp.s

.PHONY : src/buildW.s

# target to generate assembly for a file
src/buildW.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/buildW.cpp.s
.PHONY : src/buildW.cpp.s

src/contours2ucm.o: src/contours2ucm.cpp.o

.PHONY : src/contours2ucm.o

# target to build an object file
src/contours2ucm.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/contours2ucm.cpp.o
.PHONY : src/contours2ucm.cpp.o

src/contours2ucm.i: src/contours2ucm.cpp.i

.PHONY : src/contours2ucm.i

# target to preprocess a source file
src/contours2ucm.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/contours2ucm.cpp.i
.PHONY : src/contours2ucm.cpp.i

src/contours2ucm.s: src/contours2ucm.cpp.s

.PHONY : src/contours2ucm.s

# target to generate assembly for a file
src/contours2ucm.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/contours2ucm.cpp.s
.PHONY : src/contours2ucm.cpp.s

src/det_mPb.o: src/det_mPb.cpp.o

.PHONY : src/det_mPb.o

# target to build an object file
src/det_mPb.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/det_mPb.cpp.o
.PHONY : src/det_mPb.cpp.o

src/det_mPb.i: src/det_mPb.cpp.i

.PHONY : src/det_mPb.i

# target to preprocess a source file
src/det_mPb.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/det_mPb.cpp.i
.PHONY : src/det_mPb.cpp.i

src/det_mPb.s: src/det_mPb.cpp.s

.PHONY : src/det_mPb.s

# target to generate assembly for a file
src/det_mPb.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/det_mPb.cpp.s
.PHONY : src/det_mPb.cpp.s

src/detmpb.o: src/detmpb.cpp.o

.PHONY : src/detmpb.o

# target to build an object file
src/detmpb.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/detmpb.cpp.o
.PHONY : src/detmpb.cpp.o

src/detmpb.i: src/detmpb.cpp.i

.PHONY : src/detmpb.i

# target to preprocess a source file
src/detmpb.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/detmpb.cpp.i
.PHONY : src/detmpb.cpp.i

src/detmpb.s: src/detmpb.cpp.s

.PHONY : src/detmpb.s

# target to generate assembly for a file
src/detmpb.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/detmpb.cpp.s
.PHONY : src/detmpb.cpp.s

src/fit_contour.o: src/fit_contour.cpp.o

.PHONY : src/fit_contour.o

# target to build an object file
src/fit_contour.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/fit_contour.cpp.o
.PHONY : src/fit_contour.cpp.o

src/fit_contour.i: src/fit_contour.cpp.i

.PHONY : src/fit_contour.i

# target to preprocess a source file
src/fit_contour.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/fit_contour.cpp.i
.PHONY : src/fit_contour.cpp.i

src/fit_contour.s: src/fit_contour.cpp.s

.PHONY : src/fit_contour.s

# target to generate assembly for a file
src/fit_contour.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/fit_contour.cpp.s
.PHONY : src/fit_contour.cpp.s

src/fitparab.o: src/fitparab.cpp.o

.PHONY : src/fitparab.o

# target to build an object file
src/fitparab.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/fitparab.cpp.o
.PHONY : src/fitparab.cpp.o

src/fitparab.i: src/fitparab.cpp.i

.PHONY : src/fitparab.i

# target to preprocess a source file
src/fitparab.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/fitparab.cpp.i
.PHONY : src/fitparab.cpp.i

src/fitparab.s: src/fitparab.cpp.s

.PHONY : src/fitparab.s

# target to generate assembly for a file
src/fitparab.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/fitparab.cpp.s
.PHONY : src/fitparab.cpp.s

src/globalPb.o: src/globalPb.cpp.o

.PHONY : src/globalPb.o

# target to build an object file
src/globalPb.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/globalPb.cpp.o
.PHONY : src/globalPb.cpp.o

src/globalPb.i: src/globalPb.cpp.i

.PHONY : src/globalPb.i

# target to preprocess a source file
src/globalPb.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/globalPb.cpp.i
.PHONY : src/globalPb.cpp.i

src/globalPb.s: src/globalPb.cpp.s

.PHONY : src/globalPb.s

# target to generate assembly for a file
src/globalPb.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/globalPb.cpp.s
.PHONY : src/globalPb.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mex_contour_sides.o: src/mex_contour_sides.cpp.o

.PHONY : src/mex_contour_sides.o

# target to build an object file
src/mex_contour_sides.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/mex_contour_sides.cpp.o
.PHONY : src/mex_contour_sides.cpp.o

src/mex_contour_sides.i: src/mex_contour_sides.cpp.i

.PHONY : src/mex_contour_sides.i

# target to preprocess a source file
src/mex_contour_sides.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/mex_contour_sides.cpp.i
.PHONY : src/mex_contour_sides.cpp.i

src/mex_contour_sides.s: src/mex_contour_sides.cpp.s

.PHONY : src/mex_contour_sides.s

# target to generate assembly for a file
src/mex_contour_sides.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/mex_contour_sides.cpp.s
.PHONY : src/mex_contour_sides.cpp.s

src/mex_pb_parts_final_selected.o: src/mex_pb_parts_final_selected.cpp.o

.PHONY : src/mex_pb_parts_final_selected.o

# target to build an object file
src/mex_pb_parts_final_selected.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/mex_pb_parts_final_selected.cpp.o
.PHONY : src/mex_pb_parts_final_selected.cpp.o

src/mex_pb_parts_final_selected.i: src/mex_pb_parts_final_selected.cpp.i

.PHONY : src/mex_pb_parts_final_selected.i

# target to preprocess a source file
src/mex_pb_parts_final_selected.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/mex_pb_parts_final_selected.cpp.i
.PHONY : src/mex_pb_parts_final_selected.cpp.i

src/mex_pb_parts_final_selected.s: src/mex_pb_parts_final_selected.cpp.s

.PHONY : src/mex_pb_parts_final_selected.s

# target to generate assembly for a file
src/mex_pb_parts_final_selected.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/mex_pb_parts_final_selected.cpp.s
.PHONY : src/mex_pb_parts_final_selected.cpp.s

src/multiscalePb.o: src/multiscalePb.cpp.o

.PHONY : src/multiscalePb.o

# target to build an object file
src/multiscalePb.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/multiscalePb.cpp.o
.PHONY : src/multiscalePb.cpp.o

src/multiscalePb.i: src/multiscalePb.cpp.i

.PHONY : src/multiscalePb.i

# target to preprocess a source file
src/multiscalePb.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/multiscalePb.cpp.i
.PHONY : src/multiscalePb.cpp.i

src/multiscalePb.s: src/multiscalePb.cpp.s

.PHONY : src/multiscalePb.s

# target to generate assembly for a file
src/multiscalePb.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/multiscalePb.cpp.s
.PHONY : src/multiscalePb.cpp.s

src/nonmax_channels.o: src/nonmax_channels.cpp.o

.PHONY : src/nonmax_channels.o

# target to build an object file
src/nonmax_channels.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/nonmax_channels.cpp.o
.PHONY : src/nonmax_channels.cpp.o

src/nonmax_channels.i: src/nonmax_channels.cpp.i

.PHONY : src/nonmax_channels.i

# target to preprocess a source file
src/nonmax_channels.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/nonmax_channels.cpp.i
.PHONY : src/nonmax_channels.cpp.i

src/nonmax_channels.s: src/nonmax_channels.cpp.s

.PHONY : src/nonmax_channels.s

# target to generate assembly for a file
src/nonmax_channels.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/nonmax_channels.cpp.s
.PHONY : src/nonmax_channels.cpp.s

src/nonmax_oriented.o: src/nonmax_oriented.cpp.o

.PHONY : src/nonmax_oriented.o

# target to build an object file
src/nonmax_oriented.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/nonmax_oriented.cpp.o
.PHONY : src/nonmax_oriented.cpp.o

src/nonmax_oriented.i: src/nonmax_oriented.cpp.i

.PHONY : src/nonmax_oriented.i

# target to preprocess a source file
src/nonmax_oriented.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/nonmax_oriented.cpp.i
.PHONY : src/nonmax_oriented.cpp.i

src/nonmax_oriented.s: src/nonmax_oriented.cpp.s

.PHONY : src/nonmax_oriented.s

# target to generate assembly for a file
src/nonmax_oriented.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/nonmax_oriented.cpp.s
.PHONY : src/nonmax_oriented.cpp.s

src/oeFilter.o: src/oeFilter.cpp.o

.PHONY : src/oeFilter.o

# target to build an object file
src/oeFilter.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/oeFilter.cpp.o
.PHONY : src/oeFilter.cpp.o

src/oeFilter.i: src/oeFilter.cpp.i

.PHONY : src/oeFilter.i

# target to preprocess a source file
src/oeFilter.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/oeFilter.cpp.i
.PHONY : src/oeFilter.cpp.i

src/oeFilter.s: src/oeFilter.cpp.s

.PHONY : src/oeFilter.s

# target to generate assembly for a file
src/oeFilter.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/oeFilter.cpp.s
.PHONY : src/oeFilter.cpp.s

src/savgol_border.o: src/savgol_border.cpp.o

.PHONY : src/savgol_border.o

# target to build an object file
src/savgol_border.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/savgol_border.cpp.o
.PHONY : src/savgol_border.cpp.o

src/savgol_border.i: src/savgol_border.cpp.i

.PHONY : src/savgol_border.i

# target to preprocess a source file
src/savgol_border.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/savgol_border.cpp.i
.PHONY : src/savgol_border.cpp.i

src/savgol_border.s: src/savgol_border.cpp.s

.PHONY : src/savgol_border.s

# target to generate assembly for a file
src/savgol_border.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/savgol_border.cpp.s
.PHONY : src/savgol_border.cpp.s

src/spectralPb.o: src/spectralPb.cpp.o

.PHONY : src/spectralPb.o

# target to build an object file
src/spectralPb.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/spectralPb.cpp.o
.PHONY : src/spectralPb.cpp.o

src/spectralPb.i: src/spectralPb.cpp.i

.PHONY : src/spectralPb.i

# target to preprocess a source file
src/spectralPb.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/spectralPb.cpp.i
.PHONY : src/spectralPb.cpp.i

src/spectralPb.s: src/spectralPb.cpp.s

.PHONY : src/spectralPb.s

# target to generate assembly for a file
src/spectralPb.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/spectralPb.cpp.s
.PHONY : src/spectralPb.cpp.s

src/ucm_mean_pb.o: src/ucm_mean_pb.cpp.o

.PHONY : src/ucm_mean_pb.o

# target to build an object file
src/ucm_mean_pb.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/ucm_mean_pb.cpp.o
.PHONY : src/ucm_mean_pb.cpp.o

src/ucm_mean_pb.i: src/ucm_mean_pb.cpp.i

.PHONY : src/ucm_mean_pb.i

# target to preprocess a source file
src/ucm_mean_pb.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/ucm_mean_pb.cpp.i
.PHONY : src/ucm_mean_pb.cpp.i

src/ucm_mean_pb.s: src/ucm_mean_pb.cpp.s

.PHONY : src/ucm_mean_pb.s

# target to generate assembly for a file
src/ucm_mean_pb.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/ucm_mean_pb.cpp.s
.PHONY : src/ucm_mean_pb.cpp.s

src/utilities.o: src/utilities.cpp.o

.PHONY : src/utilities.o

# target to build an object file
src/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/utilities.cpp.o
.PHONY : src/utilities.cpp.o

src/utilities.i: src/utilities.cpp.i

.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/utilities.cpp.i
.PHONY : src/utilities.cpp.i

src/utilities.s: src/utilities.cpp.s

.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/utilities.cpp.s
.PHONY : src/utilities.cpp.s

src/watershed.o: src/watershed.cpp.o

.PHONY : src/watershed.o

# target to build an object file
src/watershed.cpp.o:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/watershed.cpp.o
.PHONY : src/watershed.cpp.o

src/watershed.i: src/watershed.cpp.i

.PHONY : src/watershed.i

# target to preprocess a source file
src/watershed.cpp.i:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/watershed.cpp.i
.PHONY : src/watershed.cpp.i

src/watershed.s: src/watershed.cpp.s

.PHONY : src/watershed.s

# target to generate assembly for a file
src/watershed.cpp.s:
	$(MAKE) -f CMakeFiles/ucm-mpi.dir/build.make CMakeFiles/ucm-mpi.dir/src/watershed.cpp.s
.PHONY : src/watershed.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ucm-mpi"
	@echo "... buildW"
	@echo "... CSparse"
	@echo "... damascene"
	@echo "... globalPb"
	@echo "... src/GLSVM.o"
	@echo "... src/GLSVM.i"
	@echo "... src/GLSVM.s"
	@echo "... src/MATLAB_functions.o"
	@echo "... src/MATLAB_functions.i"
	@echo "... src/MATLAB_functions.s"
	@echo "... src/SPFeatures.o"
	@echo "... src/SPFeatures.i"
	@echo "... src/SPFeatures.s"
	@echo "... src/UCMgenerator.o"
	@echo "... src/UCMgenerator.i"
	@echo "... src/UCMgenerator.s"
	@echo "... src/buildW.o"
	@echo "... src/buildW.i"
	@echo "... src/buildW.s"
	@echo "... src/contours2ucm.o"
	@echo "... src/contours2ucm.i"
	@echo "... src/contours2ucm.s"
	@echo "... src/det_mPb.o"
	@echo "... src/det_mPb.i"
	@echo "... src/det_mPb.s"
	@echo "... src/detmpb.o"
	@echo "... src/detmpb.i"
	@echo "... src/detmpb.s"
	@echo "... src/fit_contour.o"
	@echo "... src/fit_contour.i"
	@echo "... src/fit_contour.s"
	@echo "... src/fitparab.o"
	@echo "... src/fitparab.i"
	@echo "... src/fitparab.s"
	@echo "... src/globalPb.o"
	@echo "... src/globalPb.i"
	@echo "... src/globalPb.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mex_contour_sides.o"
	@echo "... src/mex_contour_sides.i"
	@echo "... src/mex_contour_sides.s"
	@echo "... src/mex_pb_parts_final_selected.o"
	@echo "... src/mex_pb_parts_final_selected.i"
	@echo "... src/mex_pb_parts_final_selected.s"
	@echo "... src/multiscalePb.o"
	@echo "... src/multiscalePb.i"
	@echo "... src/multiscalePb.s"
	@echo "... src/nonmax_channels.o"
	@echo "... src/nonmax_channels.i"
	@echo "... src/nonmax_channels.s"
	@echo "... src/nonmax_oriented.o"
	@echo "... src/nonmax_oriented.i"
	@echo "... src/nonmax_oriented.s"
	@echo "... src/oeFilter.o"
	@echo "... src/oeFilter.i"
	@echo "... src/oeFilter.s"
	@echo "... src/savgol_border.o"
	@echo "... src/savgol_border.i"
	@echo "... src/savgol_border.s"
	@echo "... src/spectralPb.o"
	@echo "... src/spectralPb.i"
	@echo "... src/spectralPb.s"
	@echo "... src/ucm_mean_pb.o"
	@echo "... src/ucm_mean_pb.i"
	@echo "... src/ucm_mean_pb.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
	@echo "... src/watershed.o"
	@echo "... src/watershed.i"
	@echo "... src/watershed.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

